export const IMAGES = {
  LOGO_HEADER: "https://i.ibb.co.com/nMLNBNcr/tekabuzz-logo.webp",
  LOGO_FOOTER: "https://i.ibb.co.com/p6Gz6XBw/tekabuzz-footer-logo.webp",
  HERO_MAIN: "https://i.ibb.co.com/VpJLpZpv/Tekka-Buzz-hero.png",
  HERO_FEATURED: "https://i.ibb.co.com/fVKZjbDY/hero-featured.png",
  FAVICON: "https://i.ibb.co.com/RLH18P9/tekkabuzz-favicon.jpg",
};

export const BANNERS = [
  "https://i.ibb.co.com/Pvvd836V/100-bonus-on-all-games-Welcome-Offer.png",
  "https://i.ibb.co.com/N23MwMp8/up-to-20-000-taka-bonus-on-Live-Casino-Table-Games-as-first-deposit-bonus-Welcome-Offer.png",
  "https://i.ibb.co.com/SwL1g5j0/20-000-taka-bonus-on-first-deposit-for-slots-fishing-welcome-offer.png",
  "https://i.ibb.co.com/tMSN2jBF/unlimited-cashback-on-all-games-weekly-promotion.png",
  "https://i.ibb.co.com/7JqnWqS0/up-to-10-000-taka-bonus-on-crash-games-Welcome-Offer.png",
  "https://i.ibb.co.com/dJgfMNns/777-taka-bonus-Ultra-Bonus-Rush-for-first-100-players-on-Facebook.png",
  "https://i.ibb.co.com/wNX2hwkc/799-taka-bonus-Quiz-Quest-Challenge.png",
  "https://i.ibb.co.com/SF5Q1cD/277-taka-telegram-join-bonus-flash-win-frenzy.png",
  "https://i.ibb.co.com/TD737YQD/300-taka-refer-bonus.png",
];

export const GAME_ICONS = {
  CASINO: "https://i.ibb.co.com/JF8WVFhP/casino.png",
  SPORT: "https://i.ibb.co.com/rRjKqgJz/sport.png",
  SLOT: "https://i.ibb.co.com/rGFL7qKQ/slot.png",
  CRASH: "https://i.ibb.co.com/W4X1JX98/crash.png",
  FISHING: "https://i.ibb.co.com/wFrmGtNK/fishing.png",
  LOTTERY: "https://i.ibb.co.com/zvmJjBg/lottery.png",
  ARCADE: "https://i.ibb.co.com/cKMD0V9x/arcade.png",
  TABLE: "https://i.ibb.co.com/sJWG5snk/table.png",
};

export const PAYMENT_ICONS = [
  { name: "bKash", url: "https://i.ibb.co.com/fVhtjjg9/bKash.webp" },
  { name: "Nagad", url: "https://i.ibb.co.com/qFMsC9SQ/Nagad.webp" },
  { name: "Rocket", url: "https://i.ibb.co.com/4nzCbKjg/rocket.webp" },
  { name: "Upay", url: "https://i.ibb.co.com/dw52WPqG/upay.webp" },
  { name: "TAP", url: "https://i.ibb.co.com/TBMv2r58/tap.webp" },
  { name: "SureCash", url: "https://i.ibb.co.com/chkXsr3k/sureCash.webp" },
  { name: "iPay", url: "https://i.ibb.co.com/gbMMkC92/iPay.webp" },
  { name: "OkWallet", url: "https://i.ibb.co.com/chv9w2Tt/okWallet.webp" },
  { name: "Bank Card", url: "https://i.ibb.co.com/bg2vvN21/bank-card.png" },
  { name: "Crypto", url: "https://i.ibb.co.com/V0gwvv41/crypto-currency.png" },
];

export const TRUST_ICONS = {
  LICENSE_CURACAO: "https://i.ibb.co.com/SDq7MTnL/gaming-curacao.webp",
  LICENSE_3: "https://i.ibb.co.com/RpWz5shN/license3-1.png",
  GAMCARE: "https://i.ibb.co.com/5qYDxTQ/icon-footer-gamcare.webp",
  AGE_18: "https://i.ibb.co.com/zTxd1WQ0/icon-footer-18.webp",
  RESP_GAMBLING: "https://i.ibb.co.com/9mm9385Q/icon-footer-responsible-gambling.webp",
  CAZVIP: "https://i.ibb.co.com/dJfVtx51/cazvip.png",
  SUPPORT_24H: "https://i.ibb.co.com/CKVR78xp/24-hour-help-support.png",
};

export const PROVIDER_LOGOS = [
  "https://i.ibb.co.com/93T6kL9m/Cricket-exchange.png",
  "https://i.ibb.co.com/M52t3nSJ/provider-exchange.png",
  "https://i.ibb.co.com/6JT1WdD0/provider-saba.png",
  "https://i.ibb.co.com/QvjMFC3D/provider-sbov2.png",
  "https://i.ibb.co.com/cSvYBsCp/provider-sbtech.png",
  "https://i.ibb.co.com/vCC5pRRh/provider-ugv3.png",
  "https://i.ibb.co.com/m5Bf6RgW/provider-cmd.png",
  "https://i.ibb.co.com/Cp74ty77/provider-awcme1sport.png",
  "https://i.ibb.co.com/gMLwWmL8/provider-awcmpinnacle.png",
  "https://i.ibb.co.com/VYGwxCFm/provider-awcmhorsebook.png",
  "https://i.ibb.co.com/YBkTCbh0/provider-rwb.png",
  "https://i.ibb.co.com/rKV92BPp/provider-jdbaspribe.png",
  "https://i.ibb.co.com/bM7bWMZw/provider-joker.png",
  "https://i.ibb.co.com/ZP5NWMF/provider-rich88.png",
  "https://i.ibb.co.com/4gnKCf6n/provider-awcmkm.png",
  "https://i.ibb.co.com/rRVpP330/provider-awcmyl.png",
  "https://i.ibb.co.com/HfmCj501/provider-ludo.png",
  "https://i.ibb.co.com/N2tBw54p/provider-awcv2-combo.png",
  "https://i.ibb.co.com/pjdSN1LV/provider-awcmladyluck.png",
  "https://i.ibb.co.com/B5k6n8jz/provider-cg.png",
  "https://i.ibb.co.com/n85h0J1N/provider-playngo.png",
  "https://i.ibb.co.com/gbnkVgjr/provider-btg.png",
  "https://i.ibb.co.com/0y380jFm/provider-netent.png",
  "https://i.ibb.co.com/60db5qM1/provider-cq9.png",
  "https://i.ibb.co.com/gQmLddN/provider-lucky365.png",
  "https://i.ibb.co.com/prb6v2gY/provider-worldmatch.png",
  "https://i.ibb.co.com/7xtwWwt2/provider-awcmiloveu.png",
  "https://i.ibb.co.com/N6wbfQRj/provider-fiveg.png",
  "https://i.ibb.co.com/0R3znV3z/provider-dragoonsoft.png",
  "https://i.ibb.co.com/qh9ZB33/provider-awcmrt.png",
  "https://i.ibb.co.com/6RS2rJH6/provider-nextspin.png",
  "https://i.ibb.co.com/mrfZ3FGD/provider-awcmsg.png",
  "https://i.ibb.co.com/gZBpRmnj/provider-awcmyesbingo.png",
  "https://i.ibb.co.com/MDQwJ4Qb/provider-awcmfastspin.png",
  "https://i.ibb.co.com/3y1d1rSV/provider-awcmfc.png",
  "https://i.ibb.co.com/chn8Fb8B/provider-jdb.png",
  "https://i.ibb.co.com/GfFx92XR/provider-pg.png",
  "https://i.ibb.co.com/spZjKhwL/provider-awcmjili.png",
  "https://i.ibb.co.com/9kYz955s/provider-awcmvia.png",
  "https://i.ibb.co.com/d0bCFXyB/provider-winfinity.png",
  "https://i.ibb.co.com/cSStGfw9/provider-bg.png",
  "https://i.ibb.co.com/hJFKHcSx/provider-awcmdg.png",
  "https://i.ibb.co.com/pjPCsVQL/provider-awcmpt.png",
  "https://i.ibb.co.com/Ng8MRqjK/provider-awcmhotroad.png",
  "https://i.ibb.co.com/7JPpT67c/provider-awcmsexy.png",
  "https://i.ibb.co.com/mrCRpf22/provider-awcmpp.png",
  "https://i.ibb.co.com/XZbZSSpT/provider-evo.png",
  "https://i.ibb.co.com/sp77ZfTR/provider-nst.png",
];
